### ISSUE TITLE
Secondary mentor by default gets id of 1

### ISSUE THREAD

**Issue by proffapt** [kossiitkgp/KWoC-Backend#94]
Whoever is the first registered mentor becomes secondary mentor of the projects for which there was no secondary mentor provided.

**Comment by harshkhandeparkar** [comment]
The secondaryMentor becomes mentor with ID `0` by default. Mentor with ID `0` should not exist in the database technically. This should be handled better in the frontend (also in the backend actually but since we are in the process of making a revamped backend, there is no point in doing this). Closing this.
